In [3]:
import numpy as np

import torch
from torch import nn
from nonlocalunet.model.blocks import *
from nonlocalunet.model.models import NonLocalUnet
from nonlocalunet.train.Metrics import mhd_score, dr_score

ModuleNotFoundError: No module named 'nonlocalunet.model'

In [5]:
X = torch.rand((4,2,16,16,16))  # b, c, d, h, w

In [3]:
gab = GlobalAggregationBlock(in_channels=1,
                             out_channels = 3,
                             ck=6,
                             cv=5,
                            query_transform='down')
gab(X).shape

torch.Size([1, 3, 8, 8, 8])

In [4]:
dsb = DownSamplingBlock(1, 4)
dsb(X).shape

torch.Size([1, 4, 8, 8, 8])

In [5]:
usb = UpSamplingBlock(1, 4, 4, 4)
usb(X).shape

torch.Size([1, 4, 32, 32, 32])

In [6]:
bb = BottomBlock(1, 4, 4)
bb(X).shape

torch.Size([1, 1, 16, 16, 16])

In [8]:
ip = InputBlock(1)
ip(X).shape

torch.Size([1, 1, 16, 16, 16])

In [ ]:
model = NonLocalUnet(1, 2)
model(X).shape

# Metrics

In [4]:
test = (np.random.rand(4,2,16,16,16)>0.5).astype('int')

In [9]:
mhd_score(test, test)

array([0., 0.])

In [7]:
dr_score(test*0, test)

array([0., 0.])

In [11]:
np.isin(np.unique([0,1]), ([0, 1]))

array([ True,  True])

In [9]:
np.isin(np.unique(test), [0, 1], invert=True)

array([False, False])

In [1]:
def unsplit_binary_mask(mask):
    """
    :param mask: binary mask of shape [B, C, D, H, W]
    :return: mask of shape [B, D, H, W] with integers of corresponding classes
    """
    img_size = mask.shape[-2:]
    mask = np.insert(mask, 0, np.zeros(img_size), axis=1)
    for i in range(mask.shape[1]):  # assign to each channel its class int
        mask[:, i, :, :] *= i
    mask = mask.argmax(axis=1)
    return mask

In [6]:
test.shape

(4, 2, 16, 16, 16)

In [11]:
unsplit_binary_mask(test[:,:,0,:,:]).shape

(4, 16, 16)